<a href="https://colab.research.google.com/github/celwyn002/Linear-algebra-58020/blob/main/Demo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.linalg import solve

A = np.array([[5,2],[4,-11]])
print(A)
B = np.array([[6],[21]])
print(B)

X = np.linalg.inv(A).dot(B)
print(X)

[[  5   2]
 [  4 -11]]
[[ 6]
 [21]]
[[ 1.71428571]
 [-1.28571429]]


In [ ]:
import numpy as np
inv_A = np.linalg.inv(A)
print(inv_A)

X = np.dot(inv_A,B)
print(X)

[[ 0.17460317  0.03174603]
 [ 0.06349206 -0.07936508]]
[[ 1.71428571]
 [-1.28571429]]


In [ ]:
X = np.linalg.solve(A,B)
print(X)

[[ 1.71428571]
 [-1.28571429]]


In [ ]:
from scipy.linalg import solve
X = solve(A,B)
print(X)

[[ 1.71428571]
 [-1.28571429]]
