<a href="https://colab.research.google.com/github/celwyn002/Linear-algebra-58020/blob/main/Determinant%20of%20Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-13.999999999999996
-14
