<a href="https://colab.research.google.com/github/celwyn002/Linear-algebra-58020/blob/main/Midterm_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.array([[12,33,2,5,5],[2,6,7,1,22],[31,15,14,12,15],[14,17,18,15,2],[20,12,26,3,4]])
print(A)

[[12 33  2  5  5]
 [ 2  6  7  1 22]
 [31 15 14 12 15]
 [14 17 18 15  2]
 [20 12 26  3  4]]


In [4]:
import numpy as np 
A = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])
print(A)


[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


In [7]:
import numpy as np

A =np.array([[6,1,6],[1,5,2],[6,2,7]])
print(A)
print("/n")
#prints transpose matrix

print(np.transpose(A))

[[6 1 6]
 [1 5 2]
 [6 2 7]]
/n
[[6 1 6]
 [1 5 2]
 [6 2 7]]


In [3]:
A=np.array(([[1,2,3],[2,3,3],[3,4,-2]]))
B=(np.linalg.inv(A))
print(B)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [6]:
import numpy as np
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))


[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


In [5]:
import numpy as np 

c = np.array([[5, 4, 1], [10, 9, 4],[10, 13, 15]])
inv_c = np.linalg.inv(c)
print(c)
print()
print(inv_c)

d = np.array([[3.4], [8.8], [19.2]])

x = np.dot(inv_c, d)
print("roots =")
print(x)

z = np.dot(c, x) #checking
print("checking =")
print(z)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
roots =
[[0.2]
 [0.4]
 [0.8]]
checking =
[[ 3.4]
 [ 8.8]
 [19.2]]
