<a href="https://colab.research.google.com/github/celwyn002/Linear-algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import numpy as np

W = np.array([[1,-3],[2,-2],[3,1]])
print("Vector W is" , W)


Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [79]:
import numpy as np

Y= np.array([[1,2,0],[0,-1,2]])
print("Vector Y is" , Y)


Vector Y is [[ 1  2  0]
 [ 0 -1  2]]


In [80]:
print(np.dot(W,Y))

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [20]:
#2 Z+Z
Z = np.array([[0,1],[2,3]])
Z = np.array([[0,1],[2,3]])
print((Z+Z))

[[0 2]
 [4 6]]


In [72]:
#3 3X
X = np.array([[[3,2,1],[-1,2,3],[2,-1,1]]])
print("Vector X is" , X)
print()
print(3*X)

Vector X is [[[ 3  2  1]
  [-1  2  3]
  [ 2 -1  1]]]

[[[ 9  6  3]
  [-3  6  9]
  [ 6 -3  3]]]


In [98]:
#2A WY-X=
Y = np.array([[1,2,0],[0,-1,2]])
W = np.array([[1,-3],[2,-2],[3,1]])
print(np.dot(Y,W)^2)

[[ 7 -5]
 [ 6  6]]


In [103]:
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])
X = np.array([[[3,2,1],[-1,2,3],[2,-1,1]]])
print(np.dot(W,Y)-X)

[[[-2  3 -7]
  [ 3  4 -7]
  [ 1  6  1]]]


In [107]:
Y = np.array([[1,2,0],[0,-1,2]])
W = np.array([[1,-3],[2,-2],[3,1]])
Z = np.array([[0,1],[2,3]])
print(np.dot(Y,W)-Z^2)

[[ 7 -6]
 [ 0  3]]
