<a href="https://colab.research.google.com/github/celwyn002/Linear-algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
C = np.zeros((4 ,4))#4 x 4 matrix 
np.fill_diagonal(C, 1 )#diagonal elements are all one (1's)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
C = np.zeros((4 ,4))#4 x 4 matrix 
np.fill_diagonal(C, 1 )#diagonal elements are all one (1's)
print("c= ")
print(C)
print("Doubled: ")# double all the values
print(2*C)

c= 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Doubled: 
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


In [7]:
# cross-product of matrices
A = np.array ([2,7,4])
B = np.array ([3,9,8])
np.cross(A,B)

array([20, -4, -3])